In [11]:
# ============================================
# Assignment 1 – Working with NumPy
# ============================================

In [12]:
import numpy as np

In [13]:
# ============================================
# 1. Create a 1D NumPy array from 1 to 20
# ============================================

In [14]:
arr = np.arange(1, 21)
print("1D Array:", arr)

# a. Calculate sum, mean, median, and standard deviation
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

# b. Find indices of elements greater than 10
indices = np.where(arr > 10)
print("Indices of elements greater than 10:", indices)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements greater than 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [15]:
# ============================================
# 2. Create a 2D NumPy array of shape 4x4
# ============================================

In [16]:
array_2d = np.arange(1, 17).reshape(4, 4)
print("\n2D Array:\n", array_2d)

# a. Transpose of the array
transpose_array = array_2d.T
print("\nTranspose of the array:\n", transpose_array)

# b. Row-wise and column-wise sums
row_sum = np.sum(array_2d, axis=1)
column_sum = np.sum(array_2d, axis=0)

print("\nRow-wise sum:", row_sum)
print("Column-wise sum:", column_sum)



2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [ ]:
# ============================================
# 3. Create two random 3x3 arrays
# ============================================

In [17]:
arr1 = np.random.randint(1,21,(3 ,3))
arr2 = np.random.randint(1,21,(3,3))

print('\nFirst Random Array:\n',arr1)
print('\nSecond Random Array:\n',arr2)

#a . Element wise operations
print("\n Element-wise Additions:\n",arr1+arr2)
print("\n Element-wise Substractons:\n",arr1-arr2)
print("\n Element-wise Multiplications:\n",arr1*arr2)

#b. Dot product of the arrays
dot_product = np.dot(arr1,arr2)
print("\nDot Product:\n",dot_product)


First Random Array:
 [[13  8 17]
 [ 5  2  3]
 [10  5 12]]

Second Random Array:
 [[20  8  1]
 [ 9 17 11]
 [ 4  2 19]]

 Element-wise Additions:
 [[33 16 18]
 [14 19 14]
 [14  7 31]]

 Element-wise Substractons:
 [[ -7   0  16]
 [ -4 -15  -8]
 [  6   3  -7]]

 Element-wise Multiplications:
 [[260  64  17]
 [ 45  34  33]
 [ 40  10 228]]

Dot Product:
 [[400 274 424]
 [130  80  84]
 [293 189 293]]


In [ ]:
# ============================================
# 4. Reshape and slice an array
# ============================================

In [19]:
#Create a 1D array of size 12
arr = np.arange(1,13)

#Reshape into 3 x 4 array
reshaped_array = arr.reshape(3,4)
print("\nReshaped 3x4 Array : \n",reshaped_array)

#Slice first two rows and last two columns 
sliced_array = reshaped_array[:2 ,-2]
print("\n Sliced Array (frist two rows , last two columns):\n",sliced_array)


Reshaped 3x4 Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Sliced Array (frist two rows , last two columns):
 [3 7]
